<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="Temporalio" />
    <PackageReference Include="Temporalio.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TemporalCommunity.Extensions.AI.IntegrationTests" />
  </ItemGroup>
</Project>
