<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>CustomWorkflow</AssemblyName>
    <!-- Samples don't need strict warning enforcement -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <UserSecretsId>922ce906-71cc-4f39-b5c3-6e9e6000216d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/TemporalCommunity.Extensions.AI/TemporalCommunity.Extensions.AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
